services:
  sumo-server:
    build:
      context: .
    command: java -jar -Djava.library.path=/usr/lib/x86_64-linux-gnu /urbanflo-sumo-server/urbanflo-sumo-server.jar
    ports:
      - 8080:8080
    restart: unless-stopped