services:
  sumo-server:
    image: ghcr.io/igloo-4002/urbanflo-sumo-server:develop
    build:
      context: .
    command: java -jar -Djava.library.path=/opt/sumo/bin /opt/urbanflo-sumo-server/urbanflo-sumo-server.jar
    ports:
      - 8080:8080
    volumes:
      - uploads:/opt/urbanflo-sumo-server/uploads
    restart: unless-stopped
volumes:
  uploads:
