services:
  sumo-server:
    build:
      context: .
    command: java -jar -Djava.library.path=/opt/sumo/bin /opt/urbanflo-sumo-server/urbanflo-sumo-server.jar
#    command: bash -c "ldd /opt/sumo/bin/sumo | grep -i 'not found'"
    ports:
      - 8080:8080
    restart: unless-stopped