services:
  sumo-server:
    # Change `:develop` to `:pr-XX` to test a PR
    #    image: ghcr.io/igloo-4002/urbanflo-sumo-server:develop
    # Uncomment the two lines below to build locally
    build:
      context: .
    command: java -jar -Djava.library.path=/opt/sumo/bin /opt/urbanflo-sumo-server/urbanflo-sumo-server.jar
    ports:
      - 8080:8080
    volumes:
      - uploads:/opt/urbanflo-sumo-server/uploads
    restart: unless-stopped
volumes:
  uploads:
