name: CI

on:
  push:
    branches:
      - develop
      - gh-actions
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Djava.library.path=/usr/lib/x86_64-linux-gnu"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Install SUMO
        run: |
          sudo apt-get update && sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:sumo/stable && sudo apt-get update
          sudo apt-get install -y sumo sumo-tools
      - name: Build
        run: gradle build
      - name: Save files
        uses: actions/upload-artifact@v3
        with:
          name: urbanflo-sumo-server
          path: |
            build/libs/*.jar
            !build/libs/*-plain.jar
            build/test-results
            LICENSE
            README.md
